name: Upload Release Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:

  build:
    name: Upload Release
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      # Initialization
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Copy configuration
        run: cp config.json.example config.json

      - run: npm ci

      # Create Chrome artifacts
      - name: Create Chrome artifacts
        run: npm run build:chrome
      - run: mkdir ./builds
      - name: Zip Artifacts
        run: cd ./dist ; zip -r ../builds/ChromeExtension.zip *
      - name: Upload ChromeExtension to release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: ChromeExtension.zip
          path: ./builds/ChromeExtension.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Create Chrome crx file
      # - name: Create Chrome CRX
      #  uses: cardinalby/webext-buildtools-chrome-crx-action@v2
      #  with:
      #    zipFilePath: ./builds/ChromeExtension.zip
      #    crxFilePath: ./builds/ChromeExtension.crx
      #    privateKey: ${{ secrets.PEM_KEY }}
      # - name: Upload Chrome.crx to release
      #  uses: Shopify/upload-to-release@v2.0.0
      #  with:
      #    name: Chrome
      #    path: ./builds/ChromeExtension.crx
      #    repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Create Firefox artifacts
      - name: Create Firefox artifacts
        run: npm run build:firefox
      - name: Zip Artifacts
        run: cd ./dist ; zip -r ../builds/FirefoxExtension.zip *
      - name: Upload FirefoxExtension to release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: FirefoxExtension.zip
          path: ./builds/FirefoxExtension.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Create Edge artifacts
      - name: Clear dist for Edge
        run: rm -rf ./dist
      - name: Create Edge artifacts
        run: npm run build:edge
      - name: Zip Artifacts
        run: cd ./dist ; zip -r ../builds/EdgeExtension.zip *
      - name: Upload EdgeExtension to release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: EdgeExtension.zip
          path: ./builds/EdgeExtension.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
